# Generated by Django 4.2 on 2025-01-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('nom', models.CharField()),
                ('rol', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_teacher', models.IntegerField()),
                ('nom', models.CharField()),
                ('cognom', models.CharField()),
                ('edat', models.IntegerField()),
                ('rol', models.CharField()),
            ],
        ),
    ]
